name: Austin Fathman
favicon: null
layout_spectrum: 0.30251
typography_spectrum: 1
title: Profile
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73829514-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1812'
    - '#4c5a67'
    - '#96959a'
    - '#797c51'
    - '#ccba90'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
