name: AustinFathman
favicon: null
layout_spectrum: 0.50482
typography_spectrum: 1
title: Austin Fathman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1812'
    - '#4c5a67'
    - '#96959a'
    - '#797c51'
    - '#ccba90'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
